/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppSavedRouteImport } from './routes/_app/saved'
import { Route as AppRoommatesRouteImport } from './routes/_app/roommates'
import { Route as AppReceiptsRouteImport } from './routes/_app/receipts'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPersonalInfoRouteImport } from './routes/_app/personal-info'
import { Route as AppPaymentsRouteImport } from './routes/_app/payments'
import { Route as AppMessagesRouteImport } from './routes/_app/messages'
import { Route as AppLanguageRouteImport } from './routes/_app/language'
import { Route as AppCompareRouteImport } from './routes/_app/compare'
import { Route as AppHostelIdRouteImport } from './routes/_app/hostel.$id'
import { Route as AppBookingIdRouteImport } from './routes/_app/booking.$id'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedRoute = AppSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AppRoute,
} as any)
const AppRoommatesRoute = AppRoommatesRouteImport.update({
  id: '/roommates',
  path: '/roommates',
  getParentRoute: () => AppRoute,
} as any)
const AppReceiptsRoute = AppReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPersonalInfoRoute = AppPersonalInfoRouteImport.update({
  id: '/personal-info',
  path: '/personal-info',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppLanguageRoute = AppLanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => AppRoute,
} as any)
const AppCompareRoute = AppCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AppRoute,
} as any)
const AppHostelIdRoute = AppHostelIdRouteImport.update({
  id: '/hostel/$id',
  path: '/hostel/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingIdRoute = AppBookingIdRouteImport.update({
  id: '/booking/$id',
  path: '/booking/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/compare': typeof AppCompareRoute
  '/language': typeof AppLanguageRoute
  '/messages': typeof AppMessagesRoute
  '/payments': typeof AppPaymentsRoute
  '/personal-info': typeof AppPersonalInfoRoute
  '/profile': typeof AppProfileRoute
  '/receipts': typeof AppReceiptsRoute
  '/roommates': typeof AppRoommatesRoute
  '/saved': typeof AppSavedRoute
  '/search': typeof AppSearchRoute
  '/api/chat': typeof ApiChatRoute
  '/booking/$id': typeof AppBookingIdRoute
  '/hostel/$id': typeof AppHostelIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/compare': typeof AppCompareRoute
  '/language': typeof AppLanguageRoute
  '/messages': typeof AppMessagesRoute
  '/payments': typeof AppPaymentsRoute
  '/personal-info': typeof AppPersonalInfoRoute
  '/profile': typeof AppProfileRoute
  '/receipts': typeof AppReceiptsRoute
  '/roommates': typeof AppRoommatesRoute
  '/saved': typeof AppSavedRoute
  '/search': typeof AppSearchRoute
  '/api/chat': typeof ApiChatRoute
  '/': typeof AppIndexRoute
  '/booking/$id': typeof AppBookingIdRoute
  '/hostel/$id': typeof AppHostelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/compare': typeof AppCompareRoute
  '/_app/language': typeof AppLanguageRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/personal-info': typeof AppPersonalInfoRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/receipts': typeof AppReceiptsRoute
  '/_app/roommates': typeof AppRoommatesRoute
  '/_app/saved': typeof AppSavedRoute
  '/_app/search': typeof AppSearchRoute
  '/api/chat': typeof ApiChatRoute
  '/_app/': typeof AppIndexRoute
  '/_app/booking/$id': typeof AppBookingIdRoute
  '/_app/hostel/$id': typeof AppHostelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/compare'
    | '/language'
    | '/messages'
    | '/payments'
    | '/personal-info'
    | '/profile'
    | '/receipts'
    | '/roommates'
    | '/saved'
    | '/search'
    | '/api/chat'
    | '/booking/$id'
    | '/hostel/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/onboarding'
    | '/compare'
    | '/language'
    | '/messages'
    | '/payments'
    | '/personal-info'
    | '/profile'
    | '/receipts'
    | '/roommates'
    | '/saved'
    | '/search'
    | '/api/chat'
    | '/'
    | '/booking/$id'
    | '/hostel/$id'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/onboarding'
    | '/_app/compare'
    | '/_app/language'
    | '/_app/messages'
    | '/_app/payments'
    | '/_app/personal-info'
    | '/_app/profile'
    | '/_app/receipts'
    | '/_app/roommates'
    | '/_app/saved'
    | '/_app/search'
    | '/api/chat'
    | '/_app/'
    | '/_app/booking/$id'
    | '/_app/hostel/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saved': {
      id: '/_app/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AppSavedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roommates': {
      id: '/_app/roommates'
      path: '/roommates'
      fullPath: '/roommates'
      preLoaderRoute: typeof AppRoommatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receipts': {
      id: '/_app/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof AppReceiptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/personal-info': {
      id: '/_app/personal-info'
      path: '/personal-info'
      fullPath: '/personal-info'
      preLoaderRoute: typeof AppPersonalInfoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/language': {
      id: '/_app/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof AppLanguageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compare': {
      id: '/_app/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof AppCompareRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hostel/$id': {
      id: '/_app/hostel/$id'
      path: '/hostel/$id'
      fullPath: '/hostel/$id'
      preLoaderRoute: typeof AppHostelIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/booking/$id': {
      id: '/_app/booking/$id'
      path: '/booking/$id'
      fullPath: '/booking/$id'
      preLoaderRoute: typeof AppBookingIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCompareRoute: typeof AppCompareRoute
  AppLanguageRoute: typeof AppLanguageRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppPersonalInfoRoute: typeof AppPersonalInfoRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReceiptsRoute: typeof AppReceiptsRoute
  AppRoommatesRoute: typeof AppRoommatesRoute
  AppSavedRoute: typeof AppSavedRoute
  AppSearchRoute: typeof AppSearchRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBookingIdRoute: typeof AppBookingIdRoute
  AppHostelIdRoute: typeof AppHostelIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCompareRoute: AppCompareRoute,
  AppLanguageRoute: AppLanguageRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppPersonalInfoRoute: AppPersonalInfoRoute,
  AppProfileRoute: AppProfileRoute,
  AppReceiptsRoute: AppReceiptsRoute,
  AppRoommatesRoute: AppRoommatesRoute,
  AppSavedRoute: AppSavedRoute,
  AppSearchRoute: AppSearchRoute,
  AppIndexRoute: AppIndexRoute,
  AppBookingIdRoute: AppBookingIdRoute,
  AppHostelIdRoute: AppHostelIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
